### PR TITLE
Localization into Russian

### PR DESCRIPTION
**Pull request by Eldrinn-Elantey**
Translation of the mod into Russian

### CODE REVIEW

**Comment by nicolas-lang** [comment]
Thanks for the PR
I'll review it later this week.

**Comment by nicolas-lang** [comment]
Short update: Your translations seems to make sense, and I'll merge them, I'll probably do the release ~ next weekend, because I am busy with work related stuff right now.

**Comment by Eldrinn-Elantey** [comment]
I hope you haven't forgotten)

**Comment by nicolas-lang** [comment]
Sorry, work is a bit busy in these troubled times...

**Pull request merged**
